/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sh.now.filmon.penjualan_motor_netbeans.screen.dashboard;

import sh.now.filmon.penjualan_motor_netbeans.screen.contract.ScreenInterface;

/**
 *
 * @author arifikhsanudin
 */
public class DashboardScreen extends javax.swing.JFrame implements ScreenInterface {

    /**
     * Creates new form Dashboard
     */
    public DashboardScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonRentalAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        refreshUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        refreshCar = new javax.swing.JButton();
        buttonUserDelete = new javax.swing.JButton();
        refreshRental = new javax.swing.JButton();
        buttonUserView = new javax.swing.JButton();
        refreshAll = new javax.swing.JButton();
        buttonUserAdd = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonCarAdd = new javax.swing.JButton();
        buttonCarView = new javax.swing.JButton();
        buttonCarDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRental = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        buttonRentalDelete = new javax.swing.JButton();
        buttonRentalView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Gilroy Light", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 102, 255));
        labelTitle.setText("Sistem Informasi Penjualan Motor");

        jLabel2.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel2.setText("Pembelian");

        buttonRentalAdd.setText("Tambah");
        buttonRentalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel4.setText("Motor");

        refreshUser.setText("Refresh");
        refreshUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel5.setText("Pembeli");

        refreshCar.setText("Refresh");
        refreshCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCarActionPerformed(evt);
            }
        });

        buttonUserDelete.setText("Hapus");
        buttonUserDelete.setEnabled(false);
        buttonUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserDeleteActionPerformed(evt);
            }
        });

        refreshRental.setText("Refresh");
        refreshRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRentalActionPerformed(evt);
            }
        });

        buttonUserView.setText("Lihat");
        buttonUserView.setEnabled(false);
        buttonUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserViewActionPerformed(evt);
            }
        });

        refreshAll.setText("Refresh Semua");
        refreshAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllActionPerformed(evt);
            }
        });

        buttonUserAdd.setText("Tambah");
        buttonUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserAddActionPerformed(evt);
            }
        });

        buttonExit.setText("Keluar");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonCarAdd.setText("Tambah");
        buttonCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarAddActionPerformed(evt);
            }
        });

        buttonCarView.setText("Lihat");
        buttonCarView.setEnabled(false);
        buttonCarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarViewActionPerformed(evt);
            }
        });

        buttonCarDelete.setText("Hapus");
        buttonCarDelete.setEnabled(false);
        buttonCarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarDeleteActionPerformed(evt);
            }
        });

        tableRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Pembeli", "Nama Motor", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRental);

        tableCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Nomor Polisi", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCar);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Alamat", "Nomor HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableUser);

        buttonRentalDelete.setText("Hapus");
        buttonRentalDelete.setEnabled(false);
        buttonRentalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalDeleteActionPerformed(evt);
            }
        });

        buttonRentalView.setText("Lihat");
        buttonRentalView.setEnabled(false);
        buttonRentalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshAll)
                        .addGap(25, 25, 25)
                        .addComponent(refreshRental)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRentalAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRentalView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRentalDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(108, 108, 108)
                                .addComponent(buttonCarAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCarView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCarDelete))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshCar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonUserAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUserView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUserDelete))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitle)
                                .addGap(263, 263, 263)
                                .addComponent(buttonExit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExit)
                    .addComponent(labelTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buttonRentalDelete)
                    .addComponent(buttonRentalView)
                    .addComponent(buttonRentalAdd)
                    .addComponent(refreshAll)
                    .addComponent(refreshRental))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(buttonCarDelete)
                    .addComponent(buttonCarView)
                    .addComponent(buttonCarAdd)
                    .addComponent(buttonUserDelete)
                    .addComponent(buttonUserView)
                    .addComponent(buttonUserAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshCar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRentalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalAddActionPerformed
//        new RentalScreen().setVisible(true);
    }//GEN-LAST:event_buttonRentalAddActionPerformed

    private void refreshUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshUserActionPerformed
//        populateTableUser();
    }//GEN-LAST:event_refreshUserActionPerformed

    private void refreshCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCarActionPerformed
//        populateTableCar();
    }//GEN-LAST:event_refreshCarActionPerformed

    private void buttonUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserDeleteActionPerformed
        Integer userId = Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
//        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
//        if (dialogResult == JOptionPane.YES_OPTION) {
//            userRepository.delete(userId);
//            populateTableUser();
//        }
    }//GEN-LAST:event_buttonUserDeleteActionPerformed

    private void refreshRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRentalActionPerformed
//        populateTableRental();
    }//GEN-LAST:event_refreshRentalActionPerformed

    private void buttonUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserViewActionPerformed
        Integer userId = Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
//        new UserScreen(userId).setVisible(true);
    }//GEN-LAST:event_buttonUserViewActionPerformed

    private void refreshAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllActionPerformed
        populateView();
    }//GEN-LAST:event_refreshAllActionPerformed

    private void buttonUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserAddActionPerformed
//        new UserScreen().setVisible(true);
    }//GEN-LAST:event_buttonUserAddActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
//        int dialogResult = JOptionPane.showConfirmDialog(null, "Keluar?", "Peringatan", JOptionPane.YES_NO_OPTION);
//        if (dialogResult == JOptionPane.YES_OPTION) {
//            this.setVisible(false);
//        }
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarAddActionPerformed
//        new CarScreen().setVisible(true);
    }//GEN-LAST:event_buttonCarAddActionPerformed

    private void buttonCarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarViewActionPerformed
        Integer carId = Integer.parseInt(tableCar.getValueAt(tableCar.getSelectedRow(), 0).toString());
//        new CarScreen(carId).setVisible(true);
    }//GEN-LAST:event_buttonCarViewActionPerformed

    private void buttonCarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarDeleteActionPerformed
        Integer carId = Integer.parseInt(tableCar.getValueAt(tableCar.getSelectedRow(), 0).toString());
//        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
//        if (dialogResult == JOptionPane.YES_OPTION) {
//            carRepository.delete(carId);
//            populateTableCar();
//        }
    }//GEN-LAST:event_buttonCarDeleteActionPerformed

    private void buttonRentalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalDeleteActionPerformed
        Integer rentalId = Integer.parseInt(tableRental.getValueAt(tableRental.getSelectedRow(), 0).toString());
//        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
//        if (dialogResult == JOptionPane.YES_OPTION) {
//            rentalRepository.delete(rentalId);
//            populateTableRental();
//        }
    }//GEN-LAST:event_buttonRentalDeleteActionPerformed

    private void buttonRentalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalViewActionPerformed
        Integer rentalId = Integer.parseInt(tableRental.getValueAt(tableRental.getSelectedRow(), 0).toString());
//        new RentalScreen(rentalId).setVisible(true);
    }//GEN-LAST:event_buttonRentalViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCarAdd;
    private javax.swing.JButton buttonCarDelete;
    private javax.swing.JButton buttonCarView;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRentalAdd;
    private javax.swing.JButton buttonRentalDelete;
    private javax.swing.JButton buttonRentalView;
    private javax.swing.JButton buttonUserAdd;
    private javax.swing.JButton buttonUserDelete;
    private javax.swing.JButton buttonUserView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JButton refreshAll;
    private javax.swing.JButton refreshCar;
    private javax.swing.JButton refreshRental;
    private javax.swing.JButton refreshUser;
    private javax.swing.JTable tableCar;
    private javax.swing.JTable tableRental;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void populateView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
